<script setup lang="ts">
import { Icon } from "@iconify/vue";
import { onMounted } from "vue";

interface Article {
  id: number;
  date: Date;
  image: string;
  title: string;
  desc: string;
  category: string;
}

const route = useRoute();
const id = route.params.id;
const articles: Array<Article> = [
  {
    id: 1,
    date: new Date(2020, 6, 1),
    image: "/consultorio/1.jpeg",
    title: "O impacto da ansiedade",
    category: "Ansiedade",
    desc: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra nam libero justo laoreet sit amet cursus sit amet. In est ante in nibh. Sit amet purus gravida quis blandit turpis cursus in hac. Ut etiam sit amet nisl purus in mollis nunc sed. Quisque non tellus orci ac. Fusce id velit ut tortor pretium viverra. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Semper eget duis at tellus at urna. Pellentesque habitant morbi tristique senectus et. Non nisi est sit amet facilisis. Est lorem ipsum dolor sit. Convallis posuere morbi leo urna molestie at elementum eu. Facilisis gravida neque convallis a. Magna fermentum iaculis eu non diam phasellus. Est ultricies integer quis auctor elit sed vulputate mi. Quisque id diam vel quam elementum pulvinar etiam non quam.</p>

<p>Elit eget gravida cum sociis natoque penatibus et. Nec tincidunt praesent semper feugiat. Rhoncus mattis rhoncus urna neque viverra. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Elementum sagittis vitae et leo duis ut diam. Convallis posuere morbi leo urna. Tempus quam pellentesque nec nam aliquam sem. Augue interdum velit euismod in pellentesque massa placerat duis. Nec tincidunt praesent semper feugiat nibh sed. Facilisis sed odio morbi quis commodo odio. Molestie at elementum eu facilisis. Mollis aliquam ut porttitor leo. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Sed pulvinar proin gravida hendrerit lectus a. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Interdum posuere lorem ipsum dolor sit. Morbi tincidunt ornare massa eget. Risus pretium quam vulputate dignissim suspendisse in est ante in.</p>

<p>Ac turpis egestas sed tempus urna et pharetra pharetra. Et netus et malesuada fames ac turpis egestas. Nec feugiat in fermentum posuere urna nec tincidunt. Nunc congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam. Sem fringilla ut morbi tincidunt. Nunc sed augue lacus viverra vitae congue eu. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Diam sit amet nisl suscipit adipiscing bibendum est. Libero nunc consequat interdum varius sit amet. Nulla aliquet enim tortor at. Iaculis eu non diam phasellus vestibulum. Eu consequat ac felis donec et. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Egestas diam in arcu cursus euismod quis viverra nibh. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Sollicitudin aliquam ultrices sagittis orci. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Sit amet risus nullam eget. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Duis at consectetur lorem donec. Nulla posuere sollicitudin aliquam ultrices. Vitae turpis massa sed elementum tempus egestas sed sed. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Vitae tempus quam pellentesque nec nam aliquam. Varius duis at consectetur lorem donec massa sapien faucibus et. Iaculis eu non diam phasellus vestibulum lorem sed. Neque egestas congue quisque egestas diam in. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Nisl rhoncus mattis rhoncus urna. Dolor magna eget est lorem ipsum dolor sit amet consectetur. At tempor commodo ullamcorper a lacus.</p>

<p>Nec ultrices dui sapien eget mi proin sed libero enim. Purus in massa tempor nec feugiat nisl pretium. Vitae proin sagittis nisl rhoncus mattis. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Commodo sed egestas egestas fringilla phasellus. Lacus sed viverra tellus in hac habitasse platea dictumst. Lorem ipsum dolor sit amet consectetur adipiscing. Vitae elementum curabitur vitae nunc sed velit dignissim. Diam vel quam elementum pulvinar etiam non. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Risus feugiat in ante metus dictum at tempor. Ultricies tristique nulla aliquet enim tortor at auctor. Diam volutpat commodo sed egestas egestas fringilla phasellus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Vitae ultricies leo integer malesuada nunc. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Tristique risus nec feugiat in fermentum posuere urna nec. Parturient montes nascetur ridiculus mus mauris. Mattis rhoncus urna neque viverra justo. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Habitant morbi tristique senectus et netus et malesuada fames ac. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Odio ut sem nulla pharetra diam sit. Pellentesque habitant morbi tristique senectus et netus. Nibh cras pulvinar mattis nunc sed blandit. Fermentum iaculis eu non diam phasellus vestibulum. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Tellus mauris a diam maecenas sed enim ut. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Id venenatis a condimentum vitae sapien pellentesque habitant. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Tristique senectus et netus et malesuada fames ac. Lectus quam id leo in vitae turpis massa sed. Quis vel eros donec ac odio tempor. Est placerat in egestas erat imperdiet sed euismod. At in tellus integer feugiat scelerisque varius morbi. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Rhoncus urna neque viverra justo nec ultrices dui. Lacus vel facilisis volutpat est velit egestas dui id ornare. Dolor sed viverra ipsum nunc aliquet bibendum enim. Morbi tincidunt augue interdum velit euismod in. Felis eget nunc lobortis mattis. Elementum pulvinar etiam non quam. Massa massa ultricies mi quis hendrerit dolor magna eget est. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Feugiat vivamus at augue eget arcu. Aliquet nibh praesent tristique magna sit amet purus. Consectetur libero id faucibus nisl tincidunt eget nullam non. Parturient montes nascetur ridiculus mus mauris. Elementum eu facilisis sed odio morbi quis commodo odio. Sagittis id consectetur purus ut faucibus pulvinar. Libero nunc consequat interdum varius sit amet mattis vulputate enim.</p>

<p>A lacus vestibulum sed arcu non odio euismod lacinia. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. In egestas erat imperdiet sed euismod nisi porta lorem. Nunc consequat interdum varius sit amet. Turpis egestas integer eget aliquet nibh. Euismod elementum nisi quis eleifend quam adipiscing. Bibendum est ultricies integer quis auctor. Commodo elit at imperdiet dui accumsan sit. Libero volutpat sed cras ornare. Dignissim convallis aenean et tortor. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Magna fringilla urna porttitor rhoncus dolor. Porttitor leo a diam sollicitudin tempor id eu nisl. Sit amet purus gravida quis blandit turpis cursus. Lobortis feugiat vivamus at augue eget arcu dictum. Integer vitae justo eget magna fermentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi.</p>`,
  },
  {
    id: 2,
    date: new Date(2020, 6, 2),
    image: "/consultorio/2.jpeg",
    title: "Lorem ipsum dolor sit amet bla bla bla bla",
    category: "Relacionamento",
    desc: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra nam libero justo laoreet sit amet cursus sit amet. In est ante in nibh. Sit amet purus gravida quis blandit turpis cursus in hac. Ut etiam sit amet nisl purus in mollis nunc sed. Quisque non tellus orci ac. Fusce id velit ut tortor pretium viverra. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Semper eget duis at tellus at urna. Pellentesque habitant morbi tristique senectus et. Non nisi est sit amet facilisis. Est lorem ipsum dolor sit. Convallis posuere morbi leo urna molestie at elementum eu. Facilisis gravida neque convallis a. Magna fermentum iaculis eu non diam phasellus. Est ultricies integer quis auctor elit sed vulputate mi. Quisque id diam vel quam elementum pulvinar etiam non quam.</p>

<p>Elit eget gravida cum sociis natoque penatibus et. Nec tincidunt praesent semper feugiat. Rhoncus mattis rhoncus urna neque viverra. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Elementum sagittis vitae et leo duis ut diam. Convallis posuere morbi leo urna. Tempus quam pellentesque nec nam aliquam sem. Augue interdum velit euismod in pellentesque massa placerat duis. Nec tincidunt praesent semper feugiat nibh sed. Facilisis sed odio morbi quis commodo odio. Molestie at elementum eu facilisis. Mollis aliquam ut porttitor leo. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Sed pulvinar proin gravida hendrerit lectus a. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Interdum posuere lorem ipsum dolor sit. Morbi tincidunt ornare massa eget. Risus pretium quam vulputate dignissim suspendisse in est ante in.</p>

<p>Ac turpis egestas sed tempus urna et pharetra pharetra. Et netus et malesuada fames ac turpis egestas. Nec feugiat in fermentum posuere urna nec tincidunt. Nunc congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam. Sem fringilla ut morbi tincidunt. Nunc sed augue lacus viverra vitae congue eu. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Diam sit amet nisl suscipit adipiscing bibendum est. Libero nunc consequat interdum varius sit amet. Nulla aliquet enim tortor at. Iaculis eu non diam phasellus vestibulum. Eu consequat ac felis donec et. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Egestas diam in arcu cursus euismod quis viverra nibh. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Sollicitudin aliquam ultrices sagittis orci. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Sit amet risus nullam eget. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Duis at consectetur lorem donec. Nulla posuere sollicitudin aliquam ultrices. Vitae turpis massa sed elementum tempus egestas sed sed. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Vitae tempus quam pellentesque nec nam aliquam. Varius duis at consectetur lorem donec massa sapien faucibus et. Iaculis eu non diam phasellus vestibulum lorem sed. Neque egestas congue quisque egestas diam in. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Nisl rhoncus mattis rhoncus urna. Dolor magna eget est lorem ipsum dolor sit amet consectetur. At tempor commodo ullamcorper a lacus.</p>

<p>Nec ultrices dui sapien eget mi proin sed libero enim. Purus in massa tempor nec feugiat nisl pretium. Vitae proin sagittis nisl rhoncus mattis. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Commodo sed egestas egestas fringilla phasellus. Lacus sed viverra tellus in hac habitasse platea dictumst. Lorem ipsum dolor sit amet consectetur adipiscing. Vitae elementum curabitur vitae nunc sed velit dignissim. Diam vel quam elementum pulvinar etiam non. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Risus feugiat in ante metus dictum at tempor. Ultricies tristique nulla aliquet enim tortor at auctor. Diam volutpat commodo sed egestas egestas fringilla phasellus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Vitae ultricies leo integer malesuada nunc. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Tristique risus nec feugiat in fermentum posuere urna nec. Parturient montes nascetur ridiculus mus mauris. Mattis rhoncus urna neque viverra justo. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Habitant morbi tristique senectus et netus et malesuada fames ac. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Odio ut sem nulla pharetra diam sit. Pellentesque habitant morbi tristique senectus et netus. Nibh cras pulvinar mattis nunc sed blandit. Fermentum iaculis eu non diam phasellus vestibulum. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Tellus mauris a diam maecenas sed enim ut. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Id venenatis a condimentum vitae sapien pellentesque habitant. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Tristique senectus et netus et malesuada fames ac. Lectus quam id leo in vitae turpis massa sed. Quis vel eros donec ac odio tempor. Est placerat in egestas erat imperdiet sed euismod. At in tellus integer feugiat scelerisque varius morbi. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Rhoncus urna neque viverra justo nec ultrices dui. Lacus vel facilisis volutpat est velit egestas dui id ornare. Dolor sed viverra ipsum nunc aliquet bibendum enim. Morbi tincidunt augue interdum velit euismod in. Felis eget nunc lobortis mattis. Elementum pulvinar etiam non quam. Massa massa ultricies mi quis hendrerit dolor magna eget est. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Feugiat vivamus at augue eget arcu. Aliquet nibh praesent tristique magna sit amet purus. Consectetur libero id faucibus nisl tincidunt eget nullam non. Parturient montes nascetur ridiculus mus mauris. Elementum eu facilisis sed odio morbi quis commodo odio. Sagittis id consectetur purus ut faucibus pulvinar. Libero nunc consequat interdum varius sit amet mattis vulputate enim.</p>

<p>A lacus vestibulum sed arcu non odio euismod lacinia. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. In egestas erat imperdiet sed euismod nisi porta lorem. Nunc consequat interdum varius sit amet. Turpis egestas integer eget aliquet nibh. Euismod elementum nisi quis eleifend quam adipiscing. Bibendum est ultricies integer quis auctor. Commodo elit at imperdiet dui accumsan sit. Libero volutpat sed cras ornare. Dignissim convallis aenean et tortor. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Magna fringilla urna porttitor rhoncus dolor. Porttitor leo a diam sollicitudin tempor id eu nisl. Sit amet purus gravida quis blandit turpis cursus. Lobortis feugiat vivamus at augue eget arcu dictum. Integer vitae justo eget magna fermentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi.</p>`,
  },
  {
    id: 3,
    date: new Date(2020, 6, 3),
    image: "/consultorio/3.jpeg",
    title: "Síndrome de Burnout",
    category: "Trabalho",
    desc: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra nam libero justo laoreet sit amet cursus sit amet. In est ante in nibh. Sit amet purus gravida quis blandit turpis cursus in hac. Ut etiam sit amet nisl purus in mollis nunc sed. Quisque non tellus orci ac. Fusce id velit ut tortor pretium viverra. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Semper eget duis at tellus at urna. Pellentesque habitant morbi tristique senectus et. Non nisi est sit amet facilisis. Est lorem ipsum dolor sit. Convallis posuere morbi leo urna molestie at elementum eu. Facilisis gravida neque convallis a. Magna fermentum iaculis eu non diam phasellus. Est ultricies integer quis auctor elit sed vulputate mi. Quisque id diam vel quam elementum pulvinar etiam non quam.</p>

<p>Elit eget gravida cum sociis natoque penatibus et. Nec tincidunt praesent semper feugiat. Rhoncus mattis rhoncus urna neque viverra. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Elementum sagittis vitae et leo duis ut diam. Convallis posuere morbi leo urna. Tempus quam pellentesque nec nam aliquam sem. Augue interdum velit euismod in pellentesque massa placerat duis. Nec tincidunt praesent semper feugiat nibh sed. Facilisis sed odio morbi quis commodo odio. Molestie at elementum eu facilisis. Mollis aliquam ut porttitor leo. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Sed pulvinar proin gravida hendrerit lectus a. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Interdum posuere lorem ipsum dolor sit. Morbi tincidunt ornare massa eget. Risus pretium quam vulputate dignissim suspendisse in est ante in.</p>

<p>Ac turpis egestas sed tempus urna et pharetra pharetra. Et netus et malesuada fames ac turpis egestas. Nec feugiat in fermentum posuere urna nec tincidunt. Nunc congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam. Sem fringilla ut morbi tincidunt. Nunc sed augue lacus viverra vitae congue eu. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Diam sit amet nisl suscipit adipiscing bibendum est. Libero nunc consequat interdum varius sit amet. Nulla aliquet enim tortor at. Iaculis eu non diam phasellus vestibulum. Eu consequat ac felis donec et. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Egestas diam in arcu cursus euismod quis viverra nibh. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Sollicitudin aliquam ultrices sagittis orci. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Sit amet risus nullam eget. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Duis at consectetur lorem donec. Nulla posuere sollicitudin aliquam ultrices. Vitae turpis massa sed elementum tempus egestas sed sed. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Vitae tempus quam pellentesque nec nam aliquam. Varius duis at consectetur lorem donec massa sapien faucibus et. Iaculis eu non diam phasellus vestibulum lorem sed. Neque egestas congue quisque egestas diam in. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Nisl rhoncus mattis rhoncus urna. Dolor magna eget est lorem ipsum dolor sit amet consectetur. At tempor commodo ullamcorper a lacus.</p>

<p>Nec ultrices dui sapien eget mi proin sed libero enim. Purus in massa tempor nec feugiat nisl pretium. Vitae proin sagittis nisl rhoncus mattis. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Commodo sed egestas egestas fringilla phasellus. Lacus sed viverra tellus in hac habitasse platea dictumst. Lorem ipsum dolor sit amet consectetur adipiscing. Vitae elementum curabitur vitae nunc sed velit dignissim. Diam vel quam elementum pulvinar etiam non. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Risus feugiat in ante metus dictum at tempor. Ultricies tristique nulla aliquet enim tortor at auctor. Diam volutpat commodo sed egestas egestas fringilla phasellus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Vitae ultricies leo integer malesuada nunc. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Tristique risus nec feugiat in fermentum posuere urna nec. Parturient montes nascetur ridiculus mus mauris. Mattis rhoncus urna neque viverra justo. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Habitant morbi tristique senectus et netus et malesuada fames ac. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Odio ut sem nulla pharetra diam sit. Pellentesque habitant morbi tristique senectus et netus. Nibh cras pulvinar mattis nunc sed blandit. Fermentum iaculis eu non diam phasellus vestibulum. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Tellus mauris a diam maecenas sed enim ut. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Id venenatis a condimentum vitae sapien pellentesque habitant. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Tristique senectus et netus et malesuada fames ac. Lectus quam id leo in vitae turpis massa sed. Quis vel eros donec ac odio tempor. Est placerat in egestas erat imperdiet sed euismod. At in tellus integer feugiat scelerisque varius morbi. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Rhoncus urna neque viverra justo nec ultrices dui. Lacus vel facilisis volutpat est velit egestas dui id ornare. Dolor sed viverra ipsum nunc aliquet bibendum enim. Morbi tincidunt augue interdum velit euismod in. Felis eget nunc lobortis mattis. Elementum pulvinar etiam non quam. Massa massa ultricies mi quis hendrerit dolor magna eget est. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Feugiat vivamus at augue eget arcu. Aliquet nibh praesent tristique magna sit amet purus. Consectetur libero id faucibus nisl tincidunt eget nullam non. Parturient montes nascetur ridiculus mus mauris. Elementum eu facilisis sed odio morbi quis commodo odio. Sagittis id consectetur purus ut faucibus pulvinar. Libero nunc consequat interdum varius sit amet mattis vulputate enim.</p>

<p>A lacus vestibulum sed arcu non odio euismod lacinia. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. In egestas erat imperdiet sed euismod nisi porta lorem. Nunc consequat interdum varius sit amet. Turpis egestas integer eget aliquet nibh. Euismod elementum nisi quis eleifend quam adipiscing. Bibendum est ultricies integer quis auctor. Commodo elit at imperdiet dui accumsan sit. Libero volutpat sed cras ornare. Dignissim convallis aenean et tortor. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Magna fringilla urna porttitor rhoncus dolor. Porttitor leo a diam sollicitudin tempor id eu nisl. Sit amet purus gravida quis blandit turpis cursus. Lobortis feugiat vivamus at augue eget arcu dictum. Integer vitae justo eget magna fermentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi.</p>`,
  },
  {
    id: 4,
    date: new Date(2020, 6, 4),
    image: "/consultorio/4.jpeg",
    title: "Lorem ipsum dolor sit amet bla bla bla bla",
    category: "Relacionamento",
    desc: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra nam libero justo laoreet sit amet cursus sit amet. In est ante in nibh. Sit amet purus gravida quis blandit turpis cursus in hac. Ut etiam sit amet nisl purus in mollis nunc sed. Quisque non tellus orci ac. Fusce id velit ut tortor pretium viverra. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Semper eget duis at tellus at urna. Pellentesque habitant morbi tristique senectus et. Non nisi est sit amet facilisis. Est lorem ipsum dolor sit. Convallis posuere morbi leo urna molestie at elementum eu. Facilisis gravida neque convallis a. Magna fermentum iaculis eu non diam phasellus. Est ultricies integer quis auctor elit sed vulputate mi. Quisque id diam vel quam elementum pulvinar etiam non quam.</p>

<p>Elit eget gravida cum sociis natoque penatibus et. Nec tincidunt praesent semper feugiat. Rhoncus mattis rhoncus urna neque viverra. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Elementum sagittis vitae et leo duis ut diam. Convallis posuere morbi leo urna. Tempus quam pellentesque nec nam aliquam sem. Augue interdum velit euismod in pellentesque massa placerat duis. Nec tincidunt praesent semper feugiat nibh sed. Facilisis sed odio morbi quis commodo odio. Molestie at elementum eu facilisis. Mollis aliquam ut porttitor leo. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Sed pulvinar proin gravida hendrerit lectus a. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Interdum posuere lorem ipsum dolor sit. Morbi tincidunt ornare massa eget. Risus pretium quam vulputate dignissim suspendisse in est ante in.</p>

<p>Ac turpis egestas sed tempus urna et pharetra pharetra. Et netus et malesuada fames ac turpis egestas. Nec feugiat in fermentum posuere urna nec tincidunt. Nunc congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam. Sem fringilla ut morbi tincidunt. Nunc sed augue lacus viverra vitae congue eu. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Diam sit amet nisl suscipit adipiscing bibendum est. Libero nunc consequat interdum varius sit amet. Nulla aliquet enim tortor at. Iaculis eu non diam phasellus vestibulum. Eu consequat ac felis donec et. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Egestas diam in arcu cursus euismod quis viverra nibh. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Sollicitudin aliquam ultrices sagittis orci. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Sit amet risus nullam eget. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Duis at consectetur lorem donec. Nulla posuere sollicitudin aliquam ultrices. Vitae turpis massa sed elementum tempus egestas sed sed. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Vitae tempus quam pellentesque nec nam aliquam. Varius duis at consectetur lorem donec massa sapien faucibus et. Iaculis eu non diam phasellus vestibulum lorem sed. Neque egestas congue quisque egestas diam in. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Nisl rhoncus mattis rhoncus urna. Dolor magna eget est lorem ipsum dolor sit amet consectetur. At tempor commodo ullamcorper a lacus.</p>

<p>Nec ultrices dui sapien eget mi proin sed libero enim. Purus in massa tempor nec feugiat nisl pretium. Vitae proin sagittis nisl rhoncus mattis. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Commodo sed egestas egestas fringilla phasellus. Lacus sed viverra tellus in hac habitasse platea dictumst. Lorem ipsum dolor sit amet consectetur adipiscing. Vitae elementum curabitur vitae nunc sed velit dignissim. Diam vel quam elementum pulvinar etiam non. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Risus feugiat in ante metus dictum at tempor. Ultricies tristique nulla aliquet enim tortor at auctor. Diam volutpat commodo sed egestas egestas fringilla phasellus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Vitae ultricies leo integer malesuada nunc. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Tristique risus nec feugiat in fermentum posuere urna nec. Parturient montes nascetur ridiculus mus mauris. Mattis rhoncus urna neque viverra justo. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Habitant morbi tristique senectus et netus et malesuada fames ac. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Odio ut sem nulla pharetra diam sit. Pellentesque habitant morbi tristique senectus et netus. Nibh cras pulvinar mattis nunc sed blandit. Fermentum iaculis eu non diam phasellus vestibulum. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Tellus mauris a diam maecenas sed enim ut. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Id venenatis a condimentum vitae sapien pellentesque habitant. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Tristique senectus et netus et malesuada fames ac. Lectus quam id leo in vitae turpis massa sed. Quis vel eros donec ac odio tempor. Est placerat in egestas erat imperdiet sed euismod. At in tellus integer feugiat scelerisque varius morbi. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Rhoncus urna neque viverra justo nec ultrices dui. Lacus vel facilisis volutpat est velit egestas dui id ornare. Dolor sed viverra ipsum nunc aliquet bibendum enim. Morbi tincidunt augue interdum velit euismod in. Felis eget nunc lobortis mattis. Elementum pulvinar etiam non quam. Massa massa ultricies mi quis hendrerit dolor magna eget est. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Feugiat vivamus at augue eget arcu. Aliquet nibh praesent tristique magna sit amet purus. Consectetur libero id faucibus nisl tincidunt eget nullam non. Parturient montes nascetur ridiculus mus mauris. Elementum eu facilisis sed odio morbi quis commodo odio. Sagittis id consectetur purus ut faucibus pulvinar. Libero nunc consequat interdum varius sit amet mattis vulputate enim.</p>

<p>A lacus vestibulum sed arcu non odio euismod lacinia. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. In egestas erat imperdiet sed euismod nisi porta lorem. Nunc consequat interdum varius sit amet. Turpis egestas integer eget aliquet nibh. Euismod elementum nisi quis eleifend quam adipiscing. Bibendum est ultricies integer quis auctor. Commodo elit at imperdiet dui accumsan sit. Libero volutpat sed cras ornare. Dignissim convallis aenean et tortor. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Magna fringilla urna porttitor rhoncus dolor. Porttitor leo a diam sollicitudin tempor id eu nisl. Sit amet purus gravida quis blandit turpis cursus. Lobortis feugiat vivamus at augue eget arcu dictum. Integer vitae justo eget magna fermentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi.</p>`,
  },
  {
    id: 5,
    date: new Date(2020, 6, 5),
    image: "/consultorio/5.jpeg",
    title: "Lorem ipsum dolor sit amet bla bla bla bla",
    category: "familia",
    desc: `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra nam libero justo laoreet sit amet cursus sit amet. In est ante in nibh. Sit amet purus gravida quis blandit turpis cursus in hac. Ut etiam sit amet nisl purus in mollis nunc sed. Quisque non tellus orci ac. Fusce id velit ut tortor pretium viverra. Nibh ipsum consequat nisl vel pretium lectus quam id leo. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Semper eget duis at tellus at urna. Pellentesque habitant morbi tristique senectus et. Non nisi est sit amet facilisis. Est lorem ipsum dolor sit. Convallis posuere morbi leo urna molestie at elementum eu. Facilisis gravida neque convallis a. Magna fermentum iaculis eu non diam phasellus. Est ultricies integer quis auctor elit sed vulputate mi. Quisque id diam vel quam elementum pulvinar etiam non quam.</p>

<p>Elit eget gravida cum sociis natoque penatibus et. Nec tincidunt praesent semper feugiat. Rhoncus mattis rhoncus urna neque viverra. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Elementum sagittis vitae et leo duis ut diam. Convallis posuere morbi leo urna. Tempus quam pellentesque nec nam aliquam sem. Augue interdum velit euismod in pellentesque massa placerat duis. Nec tincidunt praesent semper feugiat nibh sed. Facilisis sed odio morbi quis commodo odio. Molestie at elementum eu facilisis. Mollis aliquam ut porttitor leo. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Sed pulvinar proin gravida hendrerit lectus a. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Ultrices tincidunt arcu non sodales neque sodales ut etiam. Interdum posuere lorem ipsum dolor sit. Morbi tincidunt ornare massa eget. Risus pretium quam vulputate dignissim suspendisse in est ante in.</p>

<p>Ac turpis egestas sed tempus urna et pharetra pharetra. Et netus et malesuada fames ac turpis egestas. Nec feugiat in fermentum posuere urna nec tincidunt. Nunc congue nisi vitae suscipit tellus. Posuere ac ut consequat semper viverra nam. Sem fringilla ut morbi tincidunt. Nunc sed augue lacus viverra vitae congue eu. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Diam sit amet nisl suscipit adipiscing bibendum est. Libero nunc consequat interdum varius sit amet. Nulla aliquet enim tortor at. Iaculis eu non diam phasellus vestibulum. Eu consequat ac felis donec et. At urna condimentum mattis pellentesque id nibh tortor id aliquet. Egestas diam in arcu cursus euismod quis viverra nibh. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Sollicitudin aliquam ultrices sagittis orci. Mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Sit amet risus nullam eget. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Duis at consectetur lorem donec. Nulla posuere sollicitudin aliquam ultrices. Vitae turpis massa sed elementum tempus egestas sed sed. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Vitae tempus quam pellentesque nec nam aliquam. Varius duis at consectetur lorem donec massa sapien faucibus et. Iaculis eu non diam phasellus vestibulum lorem sed. Neque egestas congue quisque egestas diam in. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi. Nisl rhoncus mattis rhoncus urna. Dolor magna eget est lorem ipsum dolor sit amet consectetur. At tempor commodo ullamcorper a lacus.</p>

<p>Nec ultrices dui sapien eget mi proin sed libero enim. Purus in massa tempor nec feugiat nisl pretium. Vitae proin sagittis nisl rhoncus mattis. Volutpat ac tincidunt vitae semper quis lectus nulla at volutpat. Commodo sed egestas egestas fringilla phasellus. Lacus sed viverra tellus in hac habitasse platea dictumst. Lorem ipsum dolor sit amet consectetur adipiscing. Vitae elementum curabitur vitae nunc sed velit dignissim. Diam vel quam elementum pulvinar etiam non. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Risus feugiat in ante metus dictum at tempor. Ultricies tristique nulla aliquet enim tortor at auctor. Diam volutpat commodo sed egestas egestas fringilla phasellus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Vitae ultricies leo integer malesuada nunc. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Tristique risus nec feugiat in fermentum posuere urna nec. Parturient montes nascetur ridiculus mus mauris. Mattis rhoncus urna neque viverra justo. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Habitant morbi tristique senectus et netus et malesuada fames ac. Et magnis dis parturient montes nascetur ridiculus mus mauris vitae. Odio ut sem nulla pharetra diam sit. Pellentesque habitant morbi tristique senectus et netus. Nibh cras pulvinar mattis nunc sed blandit. Fermentum iaculis eu non diam phasellus vestibulum. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Tellus mauris a diam maecenas sed enim ut. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Id venenatis a condimentum vitae sapien pellentesque habitant. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Tristique senectus et netus et malesuada fames ac. Lectus quam id leo in vitae turpis massa sed. Quis vel eros donec ac odio tempor. Est placerat in egestas erat imperdiet sed euismod. At in tellus integer feugiat scelerisque varius morbi. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Rhoncus urna neque viverra justo nec ultrices dui. Lacus vel facilisis volutpat est velit egestas dui id ornare. Dolor sed viverra ipsum nunc aliquet bibendum enim. Morbi tincidunt augue interdum velit euismod in. Felis eget nunc lobortis mattis. Elementum pulvinar etiam non quam. Massa massa ultricies mi quis hendrerit dolor magna eget est. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Feugiat vivamus at augue eget arcu. Aliquet nibh praesent tristique magna sit amet purus. Consectetur libero id faucibus nisl tincidunt eget nullam non. Parturient montes nascetur ridiculus mus mauris. Elementum eu facilisis sed odio morbi quis commodo odio. Sagittis id consectetur purus ut faucibus pulvinar. Libero nunc consequat interdum varius sit amet mattis vulputate enim.</p>

<p>A lacus vestibulum sed arcu non odio euismod lacinia. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. In egestas erat imperdiet sed euismod nisi porta lorem. Nunc consequat interdum varius sit amet. Turpis egestas integer eget aliquet nibh. Euismod elementum nisi quis eleifend quam adipiscing. Bibendum est ultricies integer quis auctor. Commodo elit at imperdiet dui accumsan sit. Libero volutpat sed cras ornare. Dignissim convallis aenean et tortor. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Magna fringilla urna porttitor rhoncus dolor. Porttitor leo a diam sollicitudin tempor id eu nisl. Sit amet purus gravida quis blandit turpis cursus. Lobortis feugiat vivamus at augue eget arcu dictum. Integer vitae justo eget magna fermentum. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi.</p>`,
  },
];
const article: Article = articles.filter(item => item.id.toString() === id)[0];

onMounted(() => {
  window.scrollTo(0, 0);
  document.querySelector("#desc").innerHTML = article.desc;
});
</script>

<template>
  <div class="publicacao">
    <section class="bg-image">
      <Title
        :title="article.title"
        color="var(--secondary)"
        :subtitle="article.category" />
    </section>
    <div class="content">
      <span class="date">{{
        article.date.toLocaleDateString("pt-BR", {
          weekday: "long",
          year: "numeric",
          month: "long",
          day: "numeric",
        })
      }}</span>
      <p class="desc" id="desc"></p>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.publicacao {
  .bg-image {
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
    background-image: url("/publicacoes/bg.jpg");
    background-size: cover;
    background-position: center;
    width: 100%;
    height: 100%;
    height: 300px;

    * {
      z-index: 2;
    }

    &:before {
      content: "";
      position: absolute;
      inset: 0;
      background-color: rgba(255, 255, 255, 0.652);
    }
  }

  .content {
    max-width: 900px;
    background-color: #fff;
    padding: 1.5rem;
    margin: 0rem auto;
    display: flex;
    flex-direction: column;

    .date {
      color: var(--secondary);
      font-family: "WorkSansRegular";
      font-size: 1.3rem;
      margin-bottom: 2rem;
    }

    .desc {
      text-indent: 2rem;
      line-height: 2rem;
      font-size: 1.3rem;
      font-family: "WorkSansThin";
    }
  }
}
</style>
